export const PERFORMANCE_CONSTANTS = {
  MIN_LOADING_TIME: 500,
  SEARCH_FOCUS_DELAY: 100,
  FADE_OUT_DURATION: 150,
  WIDTH_RESTORE_DELAY: 200,
  SEARCH_MAX_LENGTH: 100,
} as const;

export const CONTRIBUTION_CONFIG = {
  DAYS_IN_MONTH: 30,
  TOOLTIP_OFFSET_Y: 60,
  LEVEL_THRESHOLDS: [0, 1, 3, 5] as const,
} as const;

export const CONTRIBUTION_LEVELS = {
  EMPTY: 0,
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  VERY_HIGH: 4,
} as const;
